### ISSUE TITLE
crash when backup is attempted in version 1.3.0

### ISSUE THREAD

**Issue by crabdancing** [Szum123321/textile_backup#29]
See [crash log](https://paste.ee/p/CyBEd).

Also, [here's](https://gist.github.com/alxpettit/a12fae1ca06ee3d677efdabe46e6dae2) my config file.

**Comment by Szum123321** [comment]
I'm sorry but I'm not a home today, so I can't work on this bug right now. All I can tell you right now is that indeed this crush is caused by Textile Backup Mod.

**Comment by Szum123321** [comment]
So I analized your log. Crush is caused be RejectedExecutiomException, which gets thrown when someone tries using closed executor serivece. It looks like you played on single player world, loged out and then logedin. Now I have to tell you that I used my own executor serivece, which gets shut down when server stops. Because I mainly tested this mod on servers this is not a problem. But on single player world when you relog to some world it causes an exception. I will repair it soon.

**Comment by Szum123321** [comment]
https://github.com/Szum123321/textile_backup/blob/28641383f95eb11963ec521deb76564fe8f1400d/src/main/java/net/szum123321/textile_backup/TextileBackup.java#L64

This line, to be exact, causes this issue.

**Comment by Szum123321** [comment]
Repaired in 31623906d9d539f2e4c0c4a64e479f77e8305769

**Comment by crabdancing** [comment]
Thanks! I'll open a new issue if I find any more problems! :)
