### ISSUE TITLE
Feature Request: SFTP upload

### ISSUE THREAD

**Issue by noxx4** [Szum123321/textile_backup#41]
It would be great to upload the backup to another server.

**Comment by Szum123321** [comment]
Hi!
That sounds like a good idea. I might add that at some point.

**Comment by Glucy-2** [comment]
How is it going?
I'm thinking about backing up to a FTP(S) or SFTP server, but I didn't find any fabric mod that supports 1.16 can do it. @Szum123321

**Comment by Szum123321** [comment]
Yes, I plan to implement it, although I feel like there's already too much stuff in one mod. First, I would like to split it into a few different projects, so that some features would be available as addons. I just think that textile backup in its current state might be quite overwhelming for many people.

**Comment by Szum123321** [comment]
When I find some more free time I'm going to rewrite the whole thing and leave only the most important parts. Additional compressors, SFTP upload, permission system etc. will be available as addons

**Comment by Glucy-2** [comment]
OK, thanks. I'm looking forward to it.

**Comment by Glucy-2** [comment]
Hello is it going?
